# Generated by Django 5.1.2 on 2024-11-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
    ]
